### ISSUE TITLE
Reshuffle Twitter's promoted tweets

### ISSUE THREAD

**Issue by RichardLitt** [RichardLitt/egoless-web#10]
They are disingenuously promoted.

**Comment by hackergrrl** [comment]
+1. What do you think about using an issue format string like `[Twitter] <thing to be changed>` for future organization? Or GitHub labels!

**Comment by hackergrrl** [comment]
Oh, hey: https://github.com/RichardLitt/egoless-web/blob/master/styles.css#L35

Do you still see the Promoted Tweets, regardless? They aren't present for me.

**Comment by RichardLitt** [comment]
Ha! Forgot to enable this, for some reason. Works.
